# fly.toml app configuration file generated for hermes-alpha-hunter-hg9g9q on 2026-06-05T19:17:02Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hermes-alpha-hunter-hg9g9q'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  HERMES_INFERENCE_PROVIDER = 'openrouter'
  LLM_MODEL = 'nousresearch/hermes-3-llama-3.1-70b'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-2x'
  memory = '1gb'
